- name: create new group {{ group }}
  group:
    name: "{{ group }}"
    state: present
- name: Allow {{ group }} group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ group }}"
    line: "%{{ group }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
- name: create new user {{ user }}
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    state: present
- name: add {{ user }} to sudo group
  shell: usermod -a -G sudo {{ user }}
